#键盘输入一个人的信息并存储到变量里（姓名，身份证号，年龄，性别，身高，体重），并按照格式化方式进行输出。
name=input("姓名：")
num=input("身份证：")
age=input("年龄：")
sex=input("性别：")
high=input("身高：")
weight=input("体重：")

info='''
---------------------个人信息表----------------
姓名：{name}
身份证：{num}
年龄：{age}
性别：{sex}
身高：{high}
体重：{weight}
----------------------------------------------
'''
print(info.format(name=name,num=num,age=age,sex=sex,high=high,weight=weight))
